### ISSUE TITLE
The svdm function does not seem to match the docstring, and returns unexpected output

### ISSUE THREAD

**Issue by brendanlu** [UriaMorP/mprod_package#6] opened 2023-12-08 01:21 UTC
https://github.com/UriaMorP/mprod_package/blob/f596eff32a12c11920d627ec1e0751f4fa0d4aab/mprod/decompositions/_tsvdm.py#L56-L57

This call to svd, with argument ```full_matrices=False``` appears to no longer preserve the dimensions specified in the docstring, as the tensors `u_hat` and `v_hat` end up with dimensions $m \times k \times n$ and $p \times k \times n$ respectively, where $k=\min{(m,p)}$. 

We have also noticed that `s_hat` is not a tensor, but due to numpy, is actually a $n \times k$ matrix containing the facewise diagonal singular values of $\hat{S}$ in corresponding literature. From our observations and use of this function, this seems to cause a bug futher below when reversing the transformation of $\times_3 M$ through $\times_3 M^{-1}$:

https://github.com/UriaMorP/mprod_package/blob/f596eff32a12c11920d627ec1e0751f4fa0d4aab/mprod/decompositions/_tsvdm.py#L70

Whereby a default `inv_m` function generated by `idct(x, type=dct_type, n=tube_size, axis=-1, norm='ortho')` expects a tensor input, with third dimension $n$, rather than the condensed matrix representation of the singular values. We think this produces unintended output. 

Let us know if we have missed anything. Happy to open a PR to make necessary adjustments too :)
Cheers.

**Comment by UriaMorP** [comment] 2023-12-09 17:41
Hey @brendanlu
Sorry for the delayed response, and thanks for pointing out this issue (as well as the sctypeDict, thing in the PR you sent).

First of all, the doc is indeed wrong - the function is intended to result in the "thin" SVD which, produces `(m,k,n), (k,k,n), (p,k,n)` tensors ($U,S$, and $V$, respectively) where `k=min(m,p)`.

Moreover, the docs should make it clear that, at least for the $S$ component, the result is a matrix representation of the f-diagonal tensor (which can be provided using a matrix, and this is what we are doing here). 
Suppose that `a_hat = fun_m(tensor)`, and
```
u_hat, s_hat, v_hat = svdm(tensor, fun_m,inv_m, hats = True)
```
then
```
usv = ((u_hat.transpose(2, 0, 1) * s_hat.T.reshape(n, 1, m)) @ v_hat.transpose(2, 1, 0)).transpose(1,2,0)
tensor_reconstructed = inv_m(usv) # where tensor_reconstructed == a_hat
```

This of course refers to a small part of the problem you have mentioned, that `fun_m` expects an `ndarray` to operate on its last dimension. 

For the numpy version I used for development, the dct operators worked as follows, given an ndarray `a` with last dimension `tube_size = a.shape[-1]`, `a_hat = dct(a, type=2, n=tube_size, axis=-1, norm='ortho')` is such that each tube `a_hat[i_1,i_2,...,i_{d-1},:]` is the vector` dct(a[i_1,i_2,...,i_{d-1},:], type=2, norm='ortho')` .

Similarly, the `idct` should not have changed the dimensions of the (matrix) $S$. 

This is not what's going on for newer versions, and I haven't yet found the reason why. 

I'll keep you posted once I will figure it out. Of course, any help will be very much appreciated.

Thanks,
Uria

**Comment by brendanlu** [comment] 2023-12-10 03:05
Hey @UriaMorP, thanks for getting back. Nice job on both the paper, and the package here. I have enjoyed reading both, and experimenting with your TCAM approach. 

On this issue, from another look, I now think there is perhaps an extra call to `.transpose()` which is not needed. 

https://github.com/UriaMorP/mprod_package/blob/f596eff32a12c11920d627ec1e0751f4fa0d4aab/mprod/decompositions/_tsvdm.py#L70

I think if the above is changed to...
```py3
s = inv_m(s_hat)
```
...then the call to `inv_m` may work as intended, as it seems you have already transposed `s_hat` once further up. I have briefly written up a function earlier to test it, by converting into a tensor and applying `inv_m` before converting back into matrix form, and it seems to give same result. Let me know what you think when you get around to checking it. I figure this is not a huge problem as you call the tsvdm in TCAM with `hats=True`, but might be helpful fix for any users who may directly call the `svdm` function. 

Cheers,
Brendan.

**Comment by UriaMorP** [comment] 2023-12-10 05:56
@brendanlu 
You are absolutely right that none of TCAM functionality is compromised. Indeed, TCAM is based on what you can represent in the 'hat space' (thus the erroneous call to `svdm` with `hats=True` is never made in practice).

And yet, this issue should be fixed.

Regarding your observation
> On this issue, from another look, I now think there is perhaps an extra call to `.transpose()` which is not needed.
> https://github.com/UriaMorP/mprod_package/blob/f596eff32a12c11920d627ec1e0751f4fa0d4aab/mprod/decompositions/_tsvdm.py#L70

Note that dct is just one example of an orthogonal transform. However, the general form of $\cal{A} \times_3 \mathbf{M}$ is defined by left multiplication of the tensor tube fibers by an orthogonal matrix: $\hat{\cal{A}}_{i,j,:} = \mathbf{M} \cal{A}_{i,j,:}$ and this is also the way this product is implemented by the `x_m3` function:
> https://github.com/UriaMorP/mprod_package/blob/f596eff32a12c11920d627ec1e0751f4fa0d4aab/mprod/_base.py#L78-L102

While removing the extra transpose in 
> https://github.com/UriaMorP/mprod_package/blob/f596eff32a12c11920d627ec1e0751f4fa0d4aab/mprod/decompositions/_tsvdm.py#L70

will solve the issue for fft based $\mathbf{M}$ transforms such as the DCT, it breaks the functionality of TTM (tensor times matrix) operation based $\mathbf{M}$ transforms.

I'm ashamed to admit it, but there is a good chance that this never worked for the DCT since I only tested it using TTM implementation of random $\mathbf{M}$ . See
> https://github.com/UriaMorP/mprod_package/blob/f596eff32a12c11920d627ec1e0751f4fa0d4aab/mprod/decompositions/tests/test_decompositions.py#L19-L45 

which calls 
> https://github.com/UriaMorP/mprod_package/blob/f596eff32a12c11920d627ec1e0751f4fa0d4aab/mprod/tests/_utils.py#L15-L24



---------------
### Update

In order to maintain functionality of **both** TTM  **and**  functions on tubes (e.g. dct) based transforms, I corrected the error where it initially occurs:
> https://github.com/UriaMorP/mprod_package/blob/f596eff32a12c11920d627ec1e0751f4fa0d4aab/mprod/_base.py#L100

has changed to `return A @ M.T` (that is $(\mathbf{M} \mathbf{A}^\mathbf{T})^\mathbf{T}$ ) resulting in orthogonal operation of $\mathbf{M}$ on $\mathbf{S}$ 's **rows** that are the tubes of the f-diagonal tensor $\cal{S}$ .

With this change, both transpose operations: 
> https://github.com/UriaMorP/mprod_package/blob/f596eff32a12c11920d627ec1e0751f4fa0d4aab/mprod/decompositions/_tsvdm.py#L70 
are indeed redundant, and have been removed. 

I've made the changes locally and soon will add (and run) corresponding unit-tests to make sure both dct and TTM based transformation work as intended and that `svdm` result in perfect (machine precision) reconstruction when done called without truncation. 


Once the tests are completed, I'll have to recall how to push package updates to Pypi and conda-forge. 
Thanks for your patients and your interest in our work!

Uria

**Comment by brendanlu** [comment] 2023-12-10 23:04
@UriaMorP, looks like a neat fix - I appreciate the explanations too. Indeed, I have yet to experiment with explicitly defining my own matrix for $*_M$ - only using the DCTii so far. Thanks for your time and detailed responses on this issue. 

Brendan.

**Comment by UriaMorP** [comment] 2023-12-11 15:52
@brendanlu 

Closing this issue after updating the repo and the package (both in Pypi and conda-forge). 
Changes also include the correction to _tcam.py file you have posted in your PR, so I'm closing it as well.

Again, thank you for your interest, engagement and patients!
Uria.

**Closed as completed by UriaMorP** 2023-12-11 15:52 UTC
